name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t your-dockerhub-username/personal_expenses_tracker:${{ github.sha }} .

    - name: Run tests
      run: docker run your-dockerhub-username/personal_expenses_tracker:${{ github.sha }} python -m pytest

    - name: Push to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push your-dockerhub-username/personal_expenses_tracker:${{ github.sha }}

    - name: Deploy to Kubernetes
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
        export KUBECONFIG=kubeconfig
        kubectl set image deployment/finance-tracker finance-tracker=your-dockerhub-username/personal_expenses_tracker:${{ github.sha }}

